name: 🚀 Deploy Pandora Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CERTBOT_EMAIL: ${{ secrets.CERTBOT_EMAIL }}
        with:
          envs: CERTBOT_EMAIL,CLOUDFLARE_API_TOKEN
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            echo "📥 Clonando repo pandora-nginx..."
            rm -rf pandora-nginx
            git clone git@github.com-pandora-nginx:Laboratorio-de-Analise-de-Dados/pandora-nginx.git 

            cd pandora-nginx

            echo "⚙️ Copiando configs para o container Nginx..."
            docker cp conf.d/. pandora_nginx:/etc/nginx/conf.d/

            echo "🔄 Recarregando Nginx..."
            docker exec pandora_nginx nginx -s reload

            echo "🧹 Limpando diretório clonado..."
            cd ..
            rm -rf pandora-nginx

            echo "✅ Deploy concluído com sucesso!"
